### ISSUE TITLE
Awesome Twitter Client

### ISSUE THREAD

**Issue by takatakasuppon** [lazamar/silver-magpie#14]
so good, Awesome and beautiful UI new twitter client. I like this.
The only thing is, I regret that I can't scroll up and down
the twitter timeline with the keyboard.

**Comment by lazamar** [comment]
You can! :)
If you click somewhere on the timeline you can scroll with the arrow keys.
Unfortunately chrome changed the tabbing behaviour on extensions. Previously after opening the extension with Ctrl+Shift+1 or Cmd+Shift+1, you could press Tab to start controlling the timeline with the arrow keys. Now you have to click at least once in the extension window otherwise tab closes the window.
