### ISSUE TITLE
Issue Loading After Time Without Using

### ISSUE THREAD

**Issue by galeaspablo** [lazamar/silver-magpie#2]
Whenever I haven't opened silver magpie for a while, it takes forever to open.

**Comment by lazamar** [comment]
I think this might be because the DigitalOcean image in which the Silver Magpie server is at is "put to sleep" after a certain time of inactivity. It then needs to have more resources made available to it to then provide the response. 

If that is the case, this issue should go away as more people start to use it.

**Comment by lazamar** [comment]
This is not happening anymore. The solution might have been:
- Digital Ocean might have improved it's handling of idle nodes
- The database was moved to a dedicated DB server.
- Haskell

In any case. It's now solved.
